### ISSUE TITLE
Collect and display response time's details: DNS, TCP, TLS, etc.

### ISSUE THREAD

**Issue by MickaelBergem** [HowFast/roadmap#1]
To better understand how our applications perform, we need to see the split time:

* DNS request
* TCP connection
* TLS handshake, if applicable
* HTTP request send (time took to send the request)
* HTTP wait (time to first byte)
* HTTP receive (time took to download the response)
* time spent in redirects

- [x] collect and store these metrics
- [x] design the UI to incorporate the information in an easy-to-see way (stacked graph?)

**Comment by jpcaruana** [comment]
you could find some inspiration from the Network tab in Chrome dev tools

**Comment by MickaelBergem** [comment]
The new pingcollector started collecting timing information today a couple hours ago. The backend and frontend are ready to display the data, but we will wait until this weekend before releasing the feature to end-users.

However, this update triggered a change in the way response time is measured, so current users will most likely see a significant variation in their tracked response time. The new split time measure will show the exact time spent in each phase, making the graph more comprehensive and useful.

**Comment by MickaelBergem** [comment]
This feature is now deployed, usable, and stable! :tada: :tada:  
See the announcement for more information on how the split time is measured: https://medium.com/howfast-monitoring/new-feature-detailed-response-time-64fd8693d37b
