### ISSUE TITLE
APM : a little more statistical data please :)

### ISSUE THREAD

**Issue by jpcaruana** [HowFast/roadmap#12]
Right now, the APM features shows the  Average response time for every single route

<img width="278" alt="image" src="https://user-images.githubusercontent.com/31649/64254282-5e078e00-cf1f-11e9-865a-cc6ab5f2ef0d.png">

This is great, but an average is not enough to understand what is happening. It would be great to have more statistics about every route: 

- number of hits
- median / min / max
- standard deviation etc

**Comment by jpcaruana** [comment]
Maybe another suggestion (another issue ? you tell me @MickaelBergem) : it would be great to be able to see the real raw data for every route (as for every monitor)

**Comment by MickaelBergem** [comment]
You've been heard! I'm still trying to figure out how to best represent this data, while still keeping the interface clean. The metrics you mentioned help me understand the relative importance of the data though - so thank you! I will keep this issue up to date and notify you when something is ready :)

Raw data is also a possibility, maybe once the main metrics are available.

Question for you: are you using path parameters and would like to group the routes handled by the same endpoint in Flask? The endpoint name is already collected but not used yet.

**Comment by jpcaruana** [comment]
yes it is hard to figure out how to best represent this data...

**Comment by jpcaruana** [comment]
> Question for you: are you using path parameters and would like to group the routes handled by the same endpoint in Flask? The endpoint name is already collected but not used yet.

I did not dare to suggest this... but I dreamt of it the whole night...

but depending on the parameter values (for us, a customer), you can have a huge difference in performances (from a few millis to around a minute 😱 - we have to improve)

**Comment by MickaelBergem** [comment]
@jpcaruana the first iteration of this "moar data" request is deployed to production :)

I still want to improve some parts, like adding a way to sort the table, but the data is here - now we need to determine if it's useful or if we need another way to look at the data.

Regarding the grouping by endpoint name, it will also probably get released in the next few iterations - with the ability to show URLs or endpoints (probably not "URLs corresponding to a specific endpoint" in the beginning though).

**Comment by jpcaruana** [comment]
even if presentation could be "better" (no suggestion in mind, sorry, I'm not a frontend guy), this detailed data already gives more context and this is great, thanks !

**Comment by MickaelBergem** [comment]
@jpcaruana the endpoint name is now accessible, along with the ability to sort the rows :)

![apm-sort](https://user-images.githubusercontent.com/3510190/64470409-a1b4f000-d0f7-11e9-9db1-7c0d99403d2d.gif)
