### ISSUE TITLE
Only notify if monitor is down for x consecutive pings / for y pings over 30 minutes

### ISSUE THREAD

**Issue by MickaelBergem** [HowFast/roadmap#8]
Sometimes, we don't want to be notified of small downtimes (usually less than a minute). HowFast's default monitoring interval being 60s, it often catches these small downtimes, notifying the user / team. While some users may want to get ultra-fast notifications when their server looks down, some others may want to wait for a little longer to make sure the downtime is not temporary, thus avoiding spam.

Some "notification filters" could help satisfy this category of users:

* "only notify if more than 3 consecutive failed pings"
* "only notify if more than 4 failed pings over the last 30 pings"

Use case: monitors with a low uptime standard, ...

Initial reporter: @JPCaruana

**Comment by MickaelBergem** [comment]
@jpcaruana @4ian the feature has just been released, can you try refreshing the application? :)

The feature is still in beta, please let me know if there is any inconsistency.

**Comment by 4ian** [comment]
Nice! I've adjusted the number of failed pings before getting notified, will let you know if there is wrong notifications. Super useful!
